[package]
name = "doublets"
version = "0.1.0"
authors = ["Stephen Wassell <stephen.wassell@sophos.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.7.3"
fnv = "1.0.7"
structopt = "0.3.15"
